# Screen dim/blur backdrop
general {
  hide_cursor = true
}

background {
  # use a wallpaper; falls back to solid if missing
  monitor =
  path = /home/eclypse/Downloads/artemis-2-eclipse-jupiter.jpg
  blur_passes = 0        # soft blur
  blur_size = 2
  color = rgb(255,12,16)  # fallback background
}

# Time + date
label {
  monitor =
  text = cmd[update:1000] date +"%I:%M %p"
  font_size = 64
  position = 0, 120
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:60000] date +"%A, %b %d"
  font_size = 18
  position = 0, 70
  halign = center
  valign = center
  color = rgb(200,200,210)
}

# Password field
input-field {
  monitor =
  size = 360, 48
  outline_thickness = 2
  dots_size = 0.23
  dots_spacing = 0.15
  fade_on_empty = true
  rounding = 50
  inner_color = rgba(255,255,255,0.6)
  outer_color = rgba(255,255,255,0.35)
  color = rgb(255,255,255)
#  font_size = 16
  placeholder_text = Password
  halign = center
  valign = center
}
